### 异常处理

最近修改时间：2020年11月30日



---



- 编译错误
- 运行错误



数组越界不会抛出编译异常，但是运行时则会抛出异常



#### Java 异常类架构

> 通过 `Throwable` 及其子类来描述各种不同类型的异常



##### Throwable 类

`Throwable` 位于 `java.lang` 包下，它是 Java 语言中所有错误（`Error`）和异常（`Exception`）的父类。

`Throwable` 包含了其线程创建时线程执行堆栈的快照，它提供了 `printStackTrace()` 等接口用于获取堆栈跟踪数据等信息。

主要方法：

- `fillInStackTrace`： 用当前的调用栈层次填充 `Throwable` 对象栈层次，添加到栈层次任何先前信息中；
- `getMessage`：返回关于发生的异常的详细信息。这个消息在 `Throwable` 类的构造函数中初始化了；
- `getCause`：返回一个 `Throwable` 对象代表异常原因；
- `getStackTrace`：返回一个包含堆栈层次的数组。下标为 0 的元素代表栈顶，最后一个元素代表方法调用堆栈的栈底；
- `printStackTrace`：打印 `toString()` 结果和栈层次到 `System.err`，即错误输出流



##### Error 类

`Error` 是 `Throwable` 的一个直接子类，它可以指示合理的应用程序不应该尝试捕获的**严重问题**。这些错误在应用程序的控制和处理能力之外，编译器不会检查 `Error`，对于设计合理的应用程序来说，即使发生了错误，本质上也无法通过异常处理来解决其所引起的异常状况。

常见 `Error`：

- `AssertionError`：断言错误；
- `VirtualMachineError`：虚拟机错误；
- `UnsupportedClassVersionError`：Java 类版本错误；
- `OutOfMemoryError` ：内存溢出错误。



##### Exception 类

`Exception` 是 `Throwable` 的一个直接子类。它指示合理的应用程序可能希望捕获的条件。

`Exception` 又包括 `Unchecked Exception`（非检查异常）和 `Checked Exception`（检查异常）两大类别。



###### Unchecked Exception

`Unchecked Exception` 是编译器不要求强制处理的异常，包含 `RuntimeException` 以及它的相关子类。我们编写代码时即使不去处理此类异常，程序还是会编译通过。

常见非检查异常：

- `NullPointerException`：空指针异常；
- `ArithmeticException`：算数异常；
- `ArrayIndexOutOfBoundsException`：数组下标越界异常；
- `ClassCastException`：类型转换异常。





###### Checked Exception

`Checked Exception` 是编译器要求必须处理的异常，除了 `RuntimeException` 以及它的子类，都是 `Checked Exception` 异常。我们在程序编写时就必须处理此类异常，否则程序无法编译通过。

常见检查异常：

- `IOException`：IO 异常
- `SQLException`：SQL 异常



#### 【异常处理机制】

分为两部分：

1. **抛出异常**：当一个方法发生错误时，会创建一个异常对象，并交给运行时系统处理；
2. **捕获异常**：在方法抛出异常之后，运行时系统将转为寻找合适的异常处理器。

Java 通过 5 个关键字来实现异常处理，分别是：`throw`、`throws`、`try`、`catch`、`finally`。



##### 【throw】

```java
if (b == 0) {
	throw new ArithmeticException("除数不能为0");
}
```



##### 【throws】

> 可以通过 `throws` 关键字声明方法要抛出何种类型的异常。如果一个方法可能会出现异常，但是没有能力处理这种异常，可以在方法声明处使用 `throws` 关键字来声明要抛出的异常。例如，汽车在运行时可能会出现故障，汽车本身没办法处理这个故障，那就让开车的人来处理。



```java
public void demoMethod() throws Exception1, Exception2, ... ExceptionN {
    // 可能产生异常的代码
}
```

`throws` 后面跟的异常类型列表可以有一个也可以有多个，多个则以 `,` 分割。当方法产生异常列表中的异常时，将把异常抛向方法的调用方，由调用方处理。

throws 有如下使用规则：

1. 如果方法中全部是非检查异常（即 `Error`、`RuntimeException` 以及的子类），那么可以不使用 `throws` 关键字来声明要抛出的异常，编译器能够通过编译，但在运行时会被系统抛出；
2. 如果方法中可能出现检查异常，就必须使用 `throws` 声明将其抛出或使用 `try catch` 捕获异常，否则将导致编译错误；
3. 当一个方法抛出了异常，那么该方法的调用者必须处理或者重新抛出该异常；
4. 当子类重写父类抛出异常的方法时，声明的异常必须是父类所声明异常的同类或子类。



##### 【捕获异常】

```java
try {
    // 可能会发生异常的代码块
} catch (Exception e1) {
    // 捕获并处理try抛出的异常类型Exception
} catch (Exception2 e2) {
    // 捕获并处理try抛出的异常类型Exception2
} finally {
    // 无论是否发生异常，都将执行的代码块
}

```



##### 【自定义异常】

> 自定义异常，就是定义一个类，去继承 `Throwable` 类或者它的子类。

```java
public class ExceptionDemo4 {

    static class MyCustomException extends RuntimeException {
        /**
         * 无参构造方法
         */
        public MyCustomException() {
            super("我的自定义异常");
        }
    }

    public static void main(String[] args) {
      	// 直接抛出异常
        throw new MyCustomException();
    }
}

```



##### 【异常链】

> 异常链是以一个异常对象为参数构造新的异常对象，新的异常对象将包含先前异常的信息。简单来说，就是将异常信息从底层传递给上层，逐层抛出。

```java
public class ExceptionDemo5 {

    /**
     * 第一个自定义的静态内部异常类
     */
    static class FirstCustomException extends Exception {

        // 无参构造方法
        public FirstCustomException() {
            super("第一个异常");
        }
    }

    /**
     * 第二个自定义的静态内部异常类
     */
    static class SecondCustomException extends Exception {

        public SecondCustomException() {
            super("第二个异常");
        }
    }

    /**
     * 第三个自定义的静态内部异常类
     */
    static class ThirdCustomException extends Exception {

        public ThirdCustomException() {
            super("第三个异常");
        }
    }

    /**
     * 测试异常链静态方法1，直接抛出第一个自定义的静态内部异常类
     * @throws FirstCustomException
     */
    public static void f1() throws FirstCustomException {
        throw new FirstCustomException();
    }

    /**
     * 测试异常链静态方法2，调用f1()方法，并抛出第二个自定义的静态内部异常类
     * @throws SecondCustomException
     */
    public static void f2() throws SecondCustomException {
        try {
            f1();
        } catch (FirstCustomException e) {
            throw new SecondCustomException();
        }
    }

    /**
     * 测试异常链静态方法3，调用f2()方法， 并抛出第三个自定义的静态内部异常类
     * @throws ThirdCustomException
     */
    public static void f3() throws ThirdCustomException {
        try {
            f2();
        } catch (SecondCustomException e) {
            throw new ThirdCustomException();
        }
    }

    public static void main(String[] args) throws ThirdCustomException {
        // 调用静态方法f3()
        f3();
    }
}

// 改写成异常链
/**
 * @author colorful@TaleLin
 */
public class ExceptionDemo6 {

    /**
     * 第一个自定义的静态内部异常类
     */
    static class FirstCustomException extends Exception {

        // 无参构造方法
        public FirstCustomException() {
            super("第一个异常");
        }

    }

    /**
     * 第二个自定义的静态内部异常类
     */
    static class SecondCustomException extends Exception {

        /**
         * 通过构造方法获取之前异常的信息
         * @param cause 捕获到的异常对象
         */
        public SecondCustomException(Throwable cause) {
            super("第二个异常", cause);
        }
    }

    /**
     * 第三个自定义的静态内部异常类
     */
    static class ThirdCustomException extends Exception {

        /**
         * 通过构造方法获取之前异常的信息
         * @param cause 捕获到的异常对象
         */
        public ThirdCustomException(Throwable cause) {
            super("第三个异常", cause);
        }
    }

    /**
     * 测试异常链静态方法1，直接抛出第一个自定义的静态内部异常类
     * @throws FirstCustomException
     */
    public static void f1() throws FirstCustomException {
        throw new FirstCustomException();
    }

    /**
     * 测试异常链静态方法2，调用f1()方法，并抛出第二个自定义的静态内部异常类
     * @throws SecondCustomException
     */
    public static void f2() throws SecondCustomException {
        try {
            f1();
        } catch (FirstCustomException e) {
            throw new SecondCustomException(e);
        }
    }

    /**
     * 测试异常链静态方法3，调用f2()方法， 并抛出第三个自定义的静态内部异常类
     * @throws ThirdCustomException
     */
    public static void f3() throws ThirdCustomException {
        try {
            f2();
        } catch (SecondCustomException e) {
            throw new ThirdCustomException(e);
        }
    }

    public static void main(String[] args) throws ThirdCustomException {
        // 调用静态方法f3()
        f3();
    }
}


```

